import { AlertTriangle } from "lucide-react";
import { cn } from "@/lib/utils";

export function AIDisclaimer({ compact = false, className }: { compact?: boolean; className?: string }) {
  if (compact) {
    return (
      <div className={cn("hidden sm:flex items-center gap-2 text-xs text-muted-foreground", className)}>
        <AlertTriangle className="h-3.5 w-3.5 text-primary-glow" />
        AI-generated — review before use
      </div>
    );
  }
  return (
    <div className={cn("flex items-start gap-3 rounded-lg border border-border/60 bg-muted/30 px-4 py-3 text-sm text-muted-foreground", className)}>
      <AlertTriangle className="h-4 w-4 mt-0.5 text-primary-glow shrink-0" />
      <p>
        <strong className="text-foreground">Responsible AI:</strong> Outputs are generated by AI and may be inaccurate, incomplete, or biased.
        Always review, fact-check, and edit before sharing or acting on them. Do not paste confidential or regulated data.
      </p>
    </div>
  );
}